In [90]:
import numpy as np

In [91]:
inputs = np.array([[1,1],[1,-1],[-1,1],[-1,-1]])

In [92]:
outputs = np.array([[1],[-1],[-1],[1]])

In [122]:
epochs = 10000
a = 2

In [107]:
inputneurons = 2
hiddenneurons = 2
outputneurons = 1

In [123]:
hidden_weights = np.random.uniform(size=(inputneurons,hiddenneurons),low = -0.5, high = 0.5)
hidden_bias = np.random.uniform(size=(1,hiddenneurons),low = -0.5, high = 0.5)
output_weights = np.random.uniform(size=(hiddenneurons,outputneurons),low = -0.5, high = 0.5)
output_bias = np.random.uniform(size=(1,outputneurons),low = -0.5, high = 0.5)


In [124]:
print "Hidden Weights",hidden_weights
print "Hidden Bias", hidden_bias
print "Output Weights", output_weights
print "Output Bias",output_bias

Hidden Weights [[ 0.39255036  0.1078891 ]
 [-0.09622205  0.07852233]]
Hidden Bias [[ 0.24130748 -0.42427303]]
Output Weights [[-0.11858833]
 [-0.21198539]]
Output Bias [[0.18604023]]


In [97]:
def tanh(x):
    x=x/2
    return np.tanh(x)

In [98]:
def derivative(x):
    return 0.5*(1/np.cosh(x))**2

In [125]:
for _ in range(epochs):
    

    
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = tanh(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = tanh(output_layer_activation)

    error = outputs - predicted_output
    derivative_predicted_output = error * derivative(predicted_output)
    
    error_hidden_layer = derivative_predicted_output.dot(output_weights.T)
    derivative_hidden_layer = error_hidden_layer * derivative(hidden_layer_output)

    output_weights += hidden_layer_output.T.dot(derivative_predicted_output) * a
    output_bias += np.sum(derivative_predicted_output,axis=0,keepdims=True) * a
    hidden_weights += inputs.T.dot(derivative_hidden_layer) * a
    hidden_bias += np.sum(derivative_hidden_layer,axis=0,keepdims=True) * a



In [126]:
print("Final hidden weights: ")
print(hidden_weights)
print("Final hidden bias: ")
print(hidden_bias)
print("Final output weights: ")
print(output_weights)
print("Final output bias: ")
print(output_bias)

print("\nOutput from neural network :")
print(predicted_output)

Final hidden weights: 
[[ 3.33370665  3.388196  ]
 [-3.33370665 -3.388196  ]]
Final hidden bias: 
[[ 1.74427263 -1.74875196]]
Final output weights: 
[[ 12.64582643]
 [-12.63676453]]
Final output bias: 
[[-8.77223784]]

Output from neural network :
[[ 0.99975369]
 [-0.99963337]
 [-0.99963315]
 [ 0.99975369]]
